service: demo-talk-adp-serverless

package:
  exclude:
    - OLD/**
    - .idea/**
    - .vscode-root/Cache/data_0
    - .vscode/**
    - node_modules/aws-sdk/**
    - node_modules/base64-js/**
    - node_modules/buffer/**
    - node_modules/lodash/**
    - node_modules/crypto-browserify/**
    - node_modules/ieee754/**
    - node_modules/isarray/**
    - node_modules/jmespath/**
    - node_modules/punycode/**
    - node_modules/querystring/**
    - node_modules/sax/**
    - node_modules/url/**
    - node_modules/uiid/**
    - node_modules/xml2js/**
    - node_modules/xmlbuilder/**

#
# PROJETO
#
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128

#
# FUNCOES LAMBDA
#
functions:
  v1_health_check:
    handler: /handler/health.check
    events:
      - http:
          path: /v1/health
          method: get
          cors: true
          
  v1_user_new:
    handler: /handler/user/new.run
    events:
      - http:
          path: /v1/users
          method: post
          cors: true

  v1_user_list:
    handler: /handler/user/list.run
    events:
      - http:
          path: /v1/users
          method: get
          cors: true

  v1_user_get:
    handler: /handler/user/get.run
    events:
      - http:
          path: /v1/users/{email}
          method: get
          cors: true

#
# RECURSOS
#
resources:
  Resources:
    companyTable:
          Type: 'AWS::DynamoDB::Table'
          # DependsOn: <tableName>
          Properties:
            TableName: User
            AttributeDefinitions:
              -
                AttributeName: id
                AttributeType: S
            KeySchema:
              -
                AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1